/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package ayuda.gui;

import ayuda.modelo.Componente;
import ayuda.modelo.LMComponente;
import java.awt.Color;
import java.awt.Font;
import java.io.File;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.UIManager;
import javax.swing.text.BadLocationException;
import javax.swing.text.SimpleAttributeSet;
import javax.swing.text.StyleConstants;
import javax.swing.text.StyledDocument;
import javax.xml.parsers.ParserConfigurationException;
import org.xml.sax.SAXException;
import xml.analizador.dom.JespXML;
import xml.analizador.dom.modelo.Tag;

/**
 *
 * @author pato
 */
public class GUI extends javax.swing.JFrame {
    private List<Componente> componentes; 
    private final String RUTA_XML = "ayuda"+File.separator+"ayuda.xml";

    /**
     * Creates new form GUI
     */
    public GUI() throws ParserConfigurationException, SAXException, IOException {
        initComponents();
        cargarComponentesDeXML();
        this.listaComponentes.setModel(new LMComponente(componentes));
        this.listaComponentes.setSelectedIndex(0);
        this.listaComponentesMousePressed(null);
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        listaComponentes = new javax.swing.JList();
        buscar = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        textoAyuda = new javax.swing.JTextPane();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Ayuda del lenguaje JEDI-C");

        listaComponentes.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                listaComponentesMousePressed(evt);
            }
        });
        listaComponentes.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                listaComponentesKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                listaComponentesKeyReleased(evt);
            }
        });
        jScrollPane1.setViewportView(listaComponentes);

        buscar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                buscarKeyTyped(evt);
            }
        });

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/logo_200.png"))); // NOI18N

        textoAyuda.setEditable(false);
        jScrollPane3.setViewportView(textoAyuda);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(buscar, javax.swing.GroupLayout.DEFAULT_SIZE, 164, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 453, Short.MAX_VALUE)
                        .addComponent(jLabel1))
                    .addComponent(jScrollPane3))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(buscar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 442, Short.MAX_VALUE)))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void listaComponentesMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_listaComponentesMousePressed
        Object o = listaComponentes.getSelectedValue();
        if(o instanceof Componente){
            try {
                Componente c = (Componente)o;
                ponerComponenteEnTexto(c);
            } catch (BadLocationException ex) {
                Logger.getLogger(GUI.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_listaComponentesMousePressed

    private void listaComponentesKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_listaComponentesKeyPressed
        
    }//GEN-LAST:event_listaComponentesKeyPressed

    private void listaComponentesKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_listaComponentesKeyReleased
        Object o = listaComponentes.getSelectedValue();
        if(o instanceof Componente){
            try {
                Componente c = (Componente)o;
                ponerComponenteEnTexto(c);
            } catch (BadLocationException ex) {
                Logger.getLogger(GUI.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_listaComponentesKeyReleased

    private void buscarKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_buscarKeyTyped
        if(buscar.getText().trim().equalsIgnoreCase("")){
            this.listaComponentes.setModel(new LMComponente(componentes));
        }else{
            this.listaComponentes.setModel(new LMComponente(buscar(buscar.getText())));
        }
    }//GEN-LAST:event_buscarKeyTyped

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            javax.swing.UIManager.setLookAndFeel(UIManager.getSystemLookAndFeelClassName());
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                try {
                    new GUI().setVisible(true);
                } catch (ParserConfigurationException | SAXException | IOException ex) {
                    Logger.getLogger(GUI.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField buscar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JList listaComponentes;
    private javax.swing.JTextPane textoAyuda;
    // End of variables declaration//GEN-END:variables

    private void cargarComponentesDeXML() throws ParserConfigurationException, SAXException, IOException {
        componentes = new ArrayList();
        JespXML archivo = new JespXML(RUTA_XML);
        Tag raiz = archivo.leerXML();
        
        for(Tag tComponente : raiz.getTagsHijos()){
            componentes.add(new Componente(tComponente));
        }
    }
    
    public List<Componente> buscar(String nombreComponente){
        List<Componente> filtro = new ArrayList();
        for(Componente c : componentes){
            if(c.getNombre().contains(nombreComponente)){
                filtro.add(c);
            }
        }
        return filtro;
    }

    private void ponerComponenteEnTexto(Componente c) throws BadLocationException {
        textoAyuda.setText("");
        StyledDocument sd = textoAyuda.getStyledDocument();


        SimpleAttributeSet titulo = new SimpleAttributeSet();
        StyleConstants.setFontFamily(titulo, Font.MONOSPACED);
        StyleConstants.setFontSize(titulo, 25);
        StyleConstants.setForeground(titulo, Color.BLACK);
        StyleConstants.setBold(titulo, true);

        SimpleAttributeSet codigo = new SimpleAttributeSet();
        StyleConstants.setFontFamily(codigo, Font.MONOSPACED);
        StyleConstants.setFontSize(codigo, 12);
        StyleConstants.setForeground(codigo, Color.black);

        SimpleAttributeSet tituloDefyEje = new SimpleAttributeSet();
        StyleConstants.setFontFamily(tituloDefyEje, Font.MONOSPACED);
        StyleConstants.setFontSize(tituloDefyEje, 15);
        StyleConstants.setForeground(tituloDefyEje, Color.black);
        StyleConstants.setBold(tituloDefyEje, true);
        
        sd.insertString(sd.getLength(),c.getNombre() , titulo);
        sd.insertString(sd.getLength(),"\n\nDefinición:\n" , tituloDefyEje);
        sd.insertString(sd.getLength(),c.getDefinicion() , null);
        sd.insertString(sd.getLength(),"\nEjemplo:\n" , tituloDefyEje);
        sd.insertString(sd.getLength(),c.getEjemplo() , codigo);
        textoAyuda.setCaretPosition(0);
    }
}
