package cl.gui;


import cl.bd.Conexion;
import cl.bd.DatosConexion;
import cl.modelo.Usuario;
import cl.modelo.bd.Director;
import cl.modelo.bd.Profesor;
import cl.modelo.bd.Seccion;
import cl.modelo.bd.Sede;
import cl.util.Buscar;
import cl.util.Generar;
import java.io.File;
import java.io.FileInputStream;
import java.io.FileNotFoundException;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.UIManager;

/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Pato Pérez
 */
public class Apli extends javax.swing.JFrame {
    private Conexion c;
    /**
     * Creates new form Apli
     */
    public Apli() {
        initComponents();
        conectar();
        Buscar.conectar();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel4 = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        jTextField14 = new javax.swing.JTextField();
        jButton5 = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jComboBox2 = new javax.swing.JComboBox();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        codSec = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jTextField8 = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();
        jTextField10 = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        numSec = new javax.swing.JTextField();
        jSpinner1 = new javax.swing.JSpinner();
        jSpinner2 = new javax.swing.JSpinner();
        jSpinner4 = new javax.swing.JSpinner();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox();
        jLabel3 = new javax.swing.JLabel();
        jTextField3 = new javax.swing.JTextField();
        jTextField4 = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jSpinner3 = new javax.swing.JSpinner();
        jSpinner5 = new javax.swing.JSpinner();
        jPanel3 = new javax.swing.JPanel();
        jLabel14 = new javax.swing.JLabel();
        jTextField7 = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        jTextField11 = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        jButton4 = new javax.swing.JButton();
        jLabel21 = new javax.swing.JLabel();
        jSpinner6 = new javax.swing.JSpinner();
        jSpinner7 = new javax.swing.JSpinner();
        jSpinner8 = new javax.swing.JSpinner();
        jPanel6 = new javax.swing.JPanel();
        jPanel7 = new javax.swing.JPanel();
        jButton6 = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();
        jButton7 = new javax.swing.JButton();
        jPanel8 = new javax.swing.JPanel();
        jButton8 = new javax.swing.JButton();
        jPanel9 = new javax.swing.JPanel();
        jButton9 = new javax.swing.JButton();
        jButton10 = new javax.swing.JButton();

        jButton1.setText("jButton1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder("Generador de nombres"));

        jLabel13.setText("Cantidad:");

        jButton5.setText("Generar");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel13)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextField14, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(404, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(jTextField14, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton5)
                .addContainerGap(186, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Generador de nombres", jPanel4);

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Ejerjcicios profesor"));

        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "true", "false" }));

        jLabel5.setText("Todas las secciones");

        jLabel6.setText("Año:");

        jLabel7.setText("Mes:");

        jLabel8.setText("codigo seccion:");

        jLabel9.setText("codigo profesor:");

        jLabel10.setText("Cantidad:");

        jButton3.setText("Insertar ejercicios profesor");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jLabel11.setText("Titulo ejercicio");

        jLabel12.setText("numero seccion");

        jSpinner1.setModel(new javax.swing.SpinnerNumberModel(Integer.valueOf(1), Integer.valueOf(0), null, Integer.valueOf(1)));

        jSpinner2.setModel(new javax.swing.SpinnerNumberModel(1, 1, 12, 1));

        jSpinner4.setModel(new javax.swing.SpinnerNumberModel(2010, 2010, 2100, 1));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel9)
                    .addComponent(jLabel5)
                    .addComponent(jLabel11)
                    .addComponent(jLabel8)
                    .addComponent(jLabel10))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTextField10, javax.swing.GroupLayout.DEFAULT_SIZE, 443, Short.MAX_VALUE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(codSec, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(7, 7, 7)
                                .addComponent(jLabel12)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(numSec, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jTextField8, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jSpinner1, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel6)
                                .addGap(5, 5, 5)
                                .addComponent(jSpinner4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel7)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jSpinner2, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(jButton3)
                .addGap(173, 173, 173))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(jTextField8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 43, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5)
                    .addComponent(jLabel6)
                    .addComponent(jLabel7)
                    .addComponent(jSpinner2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jSpinner4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(jTextField10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(codSec, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel12)
                    .addComponent(numSec, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(33, 33, 33)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(jSpinner1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jButton3)
                .addContainerGap())
        );

        jTabbedPane1.addTab("Ejercicios profesor", jPanel2);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Inicio sesión"));

        jLabel1.setText("Año:");

        jLabel2.setText("Mes:");

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "administrador", "director", "profesor", "alumno" }));

        jLabel3.setText("Código:");

        jTextField4.setText("50");

        jLabel4.setText("Cantidad:");

        jButton2.setText("Insertar inicios de sesión");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jSpinner3.setModel(new javax.swing.SpinnerNumberModel(1, 1, 12, 1));

        jSpinner5.setModel(new javax.swing.SpinnerNumberModel(2010, 2010, 2100, 1));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addComponent(jLabel1)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jSpinner5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(14, 14, 14)
                            .addComponent(jLabel2)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jSpinner3, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addComponent(jComboBox1, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jTextField3)
                            .addComponent(jTextField4, javax.swing.GroupLayout.DEFAULT_SIZE, 48, Short.MAX_VALUE))))
                .addContainerGap(380, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2)
                    .addComponent(jSpinner3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jSpinner5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 119, Short.MAX_VALUE)
                .addComponent(jButton2)
                .addContainerGap())
        );

        jTabbedPane1.addTab("Inicio sesion", jPanel1);

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder("Ejercicios alumnos"));

        jLabel14.setText("Año:");

        jTextField7.setText("2012");

        jLabel15.setText("Mes:");

        jTextField11.setText("01");

        jLabel17.setText("CODIGO ALUMNO");

        jButton4.setText("Insertar ejercicios ALUMNO");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jLabel21.setText("CODIGO EJERCICIO PROFESOR");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel14)
                            .addComponent(jLabel21)
                            .addComponent(jLabel17))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jSpinner8, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(jSpinner6, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jSpinner7, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(jTextField7, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel15)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTextField11, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(jButton4)))
                .addContainerGap(249, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel17)
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jSpinner6, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jSpinner7, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 11, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel21)
                    .addComponent(jSpinner8, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel14)
                    .addComponent(jLabel15))
                .addGap(32, 32, 32)
                .addComponent(jButton4)
                .addGap(110, 110, 110))
        );

        jPanel3Layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {jLabel17, jSpinner6, jSpinner7});

        jPanel3Layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {jLabel21, jSpinner8});

        jTabbedPane1.addTab("Ejercicios alumnos", jPanel3);

        jPanel7.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createTitledBorder("director"), "director"));

        jButton6.setText("generar 26 directores");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButton6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButton6)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel5.setBorder(javax.swing.BorderFactory.createTitledBorder("profesores"));

        jButton7.setText("crear 3 profesores por sede");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButton7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButton7, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel8.setBorder(javax.swing.BorderFactory.createTitledBorder("secciones"));

        jButton8.setText("crear 3 secciones por cada profesor");
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButton8)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addComponent(jButton8)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel9.setBorder(javax.swing.BorderFactory.createTitledBorder("alumnos"));

        jButton9.setText("crear 24 alumnos por cada seccion");
        jButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton9ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButton9)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButton9)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jButton10.setText("Cambiar claves");
        jButton10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton10ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(jButton10))
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jPanel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jPanel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jPanel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap(79, Short.MAX_VALUE))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton10)
                .addContainerGap(89, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Creador de usuaris", jPanel6);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 578, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 298, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        int cont = Integer.parseInt(jTextField4.getText());
        
        int i=0;
        while(i<cont){
            insertar("INSERT INTO `historial` (`nom_tab`, `cod_per`, `det_his`, `fec_his`) VALUES ("
                + "'"+jComboBox1.getSelectedItem().toString()+"', "
                + ""+jTextField3.getText()+", "
                + "'Inició sesión', "
                + "'"+jSpinner5.getValue().toString()+"-"+jSpinner3.getValue().toString()+"-24 15:18:14');");
            i++;
        }
        
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        int cont = Integer.parseInt(jSpinner1.getValue().toString());
        int i=0;
        while(i<cont){
            try {
                insertarArchivoProfesor(Boolean.valueOf(jComboBox2.getSelectedItem().toString()));
            } catch (    SQLException | FileNotFoundException ex) {
                Logger.getLogger(Apli.class.getName()).log(Level.SEVERE, null, ex);
            }
            i++;
        }
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed

        int primerCod = Integer.parseInt(jSpinner6.getValue().toString());
        int ultiCod = Integer.parseInt(jSpinner7.getValue().toString());
        
        while (primerCod <= ultiCod) {
            try {
                insertarArchivoAlumno(primerCod);
                primerCod++;
            } catch (SQLException | FileNotFoundException ex) {
                Logger.getLogger(Apli.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
            
//        }
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        List<Usuario> usuarios = Generar.usuarios(Integer.parseInt(jTextField14.getText()));
        for(Usuario u:usuarios){
            System.out.println(u);
        }
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        List<Sede> sedes = getSedes();
        List<Usuario> usuarios = Generar.usuarios(26);
//        
//        for(Usuario u : usuarios){
//            System.out.println(u.getNombre());
//        }
        Usuario u;
        int i=0;
        for(Sede s: sedes){
            u = usuarios.get(i);
            
            if(s.getNombre().equalsIgnoreCase("Rancagua")){
                u.setNombre("Pedro Gonzalez Albornoz");
                u.setMail("patodeath@gmail.com");
                u.setNombreUsuario("pgonzalez");
                System.out.println("Director rancagua: "+u.getNombreUsuario());
            }
            
            if (Buscar.isDirector(u.getNombreUsuario())) {
                int numeroSiguiente = Buscar.getNextContador("director", "usu_dir", u.getNombreUsuario());
                u.setNombreUsuario(u.getNombreUsuario()+numeroSiguiente);
            }
            
            try {
                c.sentencia = c.con.createStatement();
                c.sentencia.execute("insert into director "
                        + "(nom_dir, usu_dir, pas_dir, cod_sed, ema_dir, est_dir) "
                        + "values('"+u.getNombre()+"',"
                        + "'"+u.getNombreUsuario()+"',"
                        + "'"+u.getPass()+"',"
                        + "'"+s.getCodigo()+"',"
                        + "'"+u.getMail()+"','vigente')");
                c.sentencia.close();
            } catch (SQLException ex) {
                Logger.getLogger(Apli.class.getName()).log(Level.SEVERE, null, ex);
            }
            i++;
        }
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        List<Director> directores = this.getDirectores();
        
        for(Director d: directores){
            insertarProfesor(d, 3);
        }
    }//GEN-LAST:event_jButton7ActionPerformed

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
        List<Profesor> profesores = this.getProfesores();
        
        int i=0;
        for(Profesor p: profesores){
            try {
                i++;
                c.sentencia = c.con.createStatement();
                c.sentencia.execute("insert into seccion(num_sec, cod_pro) values('"+i+"', '"+p.getCodigo()+"')");
                c.sentencia.close();
                
                i++;
                c.sentencia = c.con.createStatement();
                c.sentencia.execute("insert into seccion(num_sec, cod_pro) values('"+i+"', '"+p.getCodigo()+"')");
                c.sentencia.close();
                
                i++;
                c.sentencia = c.con.createStatement();
                c.sentencia.execute("insert into seccion(num_sec, cod_pro) values('"+i+"', '"+p.getCodigo()+"')");
                c.sentencia.close();
            } catch (SQLException ex) {
                Logger.getLogger(Apli.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_jButton8ActionPerformed

    private void jButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton9ActionPerformed
        List<Seccion> secciones = this.getSecciones();
        
        for(Seccion s: secciones){
            insertarAlumno(s, 24);
            System.out.println("Seccion "+s.getNumero()+" Lista");
        }
    }//GEN-LAST:event_jButton9ActionPerformed

    private void jButton10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton10ActionPerformed
        updatearClave("director", "pas_dir", "07091988");
        updatearClave("profesor", "pas_pro", "07091988");
        updatearClave("alumno", "pas_alu", "07091988");
    }//GEN-LAST:event_jButton10ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /*
         * Set the Nimbus look and feel
         */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /*
         * If Nimbus (introduced in Java SE 6) is not available, stay with the
         * default look and feel. For details see
         * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            javax.swing.UIManager.setLookAndFeel(UIManager.getSystemLookAndFeelClassName());
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Apli.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /*
         * Create and display the form
         */
        java.awt.EventQueue.invokeLater(new Runnable() {

            @Override
            public void run() {
                new Apli().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField codSec;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JComboBox jComboBox1;
    private javax.swing.JComboBox jComboBox2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JSpinner jSpinner1;
    private javax.swing.JSpinner jSpinner2;
    private javax.swing.JSpinner jSpinner3;
    private javax.swing.JSpinner jSpinner4;
    private javax.swing.JSpinner jSpinner5;
    private javax.swing.JSpinner jSpinner6;
    private javax.swing.JSpinner jSpinner7;
    private javax.swing.JSpinner jSpinner8;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTextField jTextField10;
    private javax.swing.JTextField jTextField11;
    private javax.swing.JTextField jTextField14;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField7;
    private javax.swing.JTextField jTextField8;
    private javax.swing.JTextField numSec;
    // End of variables declaration//GEN-END:variables

    private void conectar() {
        try {
            c = new Conexion(new DatosConexion() {

                @Override
                public String getServer() {
                    return "localhost";
                }

                @Override
                public String getUser() {
                    return "root";
                }

                @Override
                public String getPass() {
                    return "07091988";
                }

                @Override
                public String getBaseDeDatos() {
                    return "jedic";
                }
            });
            c.conectar();
        } catch (ClassNotFoundException | SQLException ex) {
            Logger.getLogger(Apli.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    private void insertar(String string) {
        try {
            c.sentencia = c.con.createStatement();
            c.sentencia.execute(string);
            c.sentencia.close();
        } catch (SQLException ex) {
            Logger.getLogger(Apli.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    
    public void insertarArchivoProfesor(boolean its) throws SQLException, FileNotFoundException {
//        if (!its) {
//            seccion = (Seccion) cboSecSub.getSelectedItem();
//            Profesor.CODIGO_SECCION = seccion.getCodigo();
//        }
        System.out.println(its);
        String fecha = jSpinner4.getValue().toString() + "-" + jSpinner1.getValue().toString() + "-01";
        String sql = "INSERT INTO ejercicio_profesor(" + (its ? "" : "cod_sec, ") + " nom_eje, eje_pro, fec_eje, fec_cre, tod_sec, des_eje, cod_pro) "
                + "VALUES (" + (its ? "" : "'" + codSec.getText() + "',") + "'" + jTextField10.getText() + "',?,'" + fecha + " 00:00', '" + jSpinner4.getValue().toString() + "-" + jSpinner1.getValue().toString() + "-01 20:00', '" + (its ? "si" : "no") + "','Descripción', '" + jTextField8.getText() + "')";
        //Creamos una cadena para después prepararla


        PreparedStatement stmt = c.con.prepareStatement(sql);
        FileInputStream fis = new FileInputStream(new File("ejercicioProfesor.txt"));
        //Lo convertimos en un Stream
        stmt.setBinaryStream(1, fis, (int) new File("ejercicioProfesor.txt").length());
        //Asignamos el Stream al Statement
        stmt.execute();

        if (its) {
            insertar("INSERT INTO `historial` (`nom_tab`, `cod_per`, `det_his`, `fec_his`) VALUES ("
                + "'profesor', "
                + ""+jTextField8.getText()+", "
                + "'"+"Ha subido un ejercicio para sus secciones: [nombre=" + jTextField10.getText() + ", descripcion=Descripción]"+"', "
                + "'"+jSpinner4.getValue().toString()+"-"+jSpinner1.getValue().toString()+"-01 20:00:00');");
//            Historial.addHistorial("Ha subido un ejercicio para sus secciones: [nombre=" + jTextField10.getText() + ", descripcion=Descripción]");
        } else {
            insertar("INSERT INTO `historial` (`nom_tab`, `cod_per`, `det_his`, `fec_his`) VALUES ("
                + "'profesor', "
                + ""+jTextField8.getText()+", "
                + "'"+"Ha subido un ejercicio para la sección " + numSec.getText() + ": [nombre=" + jTextField10.getText() + ", descripcion=Descripción]"+"', "
                + "'"+jSpinner4.getValue().toString()+"-"+jSpinner1.getValue().toString()+"-01 20:00:00');");
        }

    }
    
    public void insertarArchivoAlumno(int codAlu) throws SQLException, FileNotFoundException {
        String sql = "INSERT INTO ejercicio_alumno(cod_alu, eje_alu, eje_pro, fec_eje) "
                + "VALUES (" + codAlu + ",?,'" + jSpinner8.getValue().toString() + "','"+jTextField7.getText()+"-"+jTextField11.getText()+"-01 20:00:00')";
        //Creamos una cadena para después prepararla
        PreparedStatement stmt = c.con.prepareStatement(sql);
        FileInputStream fis = new FileInputStream(new File("ejercicioAlumno.txt"));
        //Lo convertimos en un Stream
        stmt.setBinaryStream(1, fis, (int) new File("ejercicioAlumno.txt").length());
        //Asignamos el Stream al Statement
        stmt.execute();
        
        insertar("INSERT INTO `historial` (`nom_tab`, `cod_per`, `det_his`, `fec_his`) VALUES ("
                + "'alumno', "
                + ""+codAlu+", "
                + "'"+"Envió un ejercicio en respuesta a un ejercicio de profesor: [ejercicio=GENERADO, "
                + "descripción=GENERADO]"+"', "
                + "'"+jTextField7.getText()+"-"+jTextField11.getText()+"-01 20:00:00');");
    }

    private List<Sede> getSedes() {
        List<Sede> sedes = new ArrayList<>();
        try {
            
            c.sentencia = c.con.createStatement();
            c.rs = c.sentencia.executeQuery("select * from sede");
            
            while(c.rs.next()){
                sedes.add(new Sede(c.rs.getString("cod_sed"), c.rs.getString("nom_sed")));
            }
            
            c.sentencia.close();
        } catch (SQLException ex) {
            Logger.getLogger(Apli.class.getName()).log(Level.SEVERE, null, ex);
        }finally{
            return sedes;
        }
    }
    
    private List<Director> getDirectores() {
        List<Director> directores = new ArrayList<>();
        try {
            
            c.sentencia = c.con.createStatement();
            c.rs = c.sentencia.executeQuery("select * from director");
            
            while(c.rs.next()){
                directores.add(new Director(
                        c.rs.getString("cod_sed"), 
                        c.rs.getString("est_dir"), 
                        c.rs.getString("ema_dir"), 
                        c.rs.getString("cod_dir"),
                        c.rs.getString("nom_dir"), 
                        c.rs.getString("usu_dir")));
            }
            c.sentencia.close();
        } catch (SQLException ex) {
            Logger.getLogger(Apli.class.getName()).log(Level.SEVERE, null, ex);
        }finally{
            return directores;
        }
    }
    
    private List<Profesor> getProfesores() {
        List<Profesor> profesores = new ArrayList<>();
        try {
            
            c.sentencia = c.con.createStatement();
            c.rs = c.sentencia.executeQuery("select * from profesor");
            
            while(c.rs.next()){
                profesores.add(new Profesor(
                        c.rs.getString("cod_dir"), 
                        c.rs.getString("est_pro"), 
                        c.rs.getString("ema_pro"), 
                        c.rs.getString("cod_pro"),
                        c.rs.getString("nom_pro"), 
                        c.rs.getString("usu_pro")));
            }
            c.sentencia.close();
        } catch (SQLException ex) {
            Logger.getLogger(Apli.class.getName()).log(Level.SEVERE, null, ex);
        }finally{
            return profesores;
        }
    }
    
    private List<Seccion> getSecciones() {
        List<Seccion> secciones = new ArrayList<>();
        try {
            
            c.sentencia = c.con.createStatement();
            c.rs = c.sentencia.executeQuery("select * from seccion");
            
            while(c.rs.next()){
                secciones.add(new Seccion(
                        c.rs.getString("num_sec"), 
                        c.rs.getString("cod_sec")));
            }
            c.sentencia.close();
        } catch (SQLException ex) {
            Logger.getLogger(Apli.class.getName()).log(Level.SEVERE, null, ex);
        }finally{
            return secciones;
        }
    }

    private void insertarAlumno(Seccion s, int cantidadDeAlumnos) {
        List<Usuario> usus = Generar.usuarios(cantidadDeAlumnos);
        for(Usuario u:usus ){
            try {
                if (Buscar.isAlumno(u.getNombreUsuario())) {
                    int numeroSiguiente = Buscar.getNextContador("alumno", "usu_alu", u.getNombreUsuario());
                    u.setNombreUsuario(u.getNombreUsuario()+numeroSiguiente);
                }
                c.sentencia = c.con.createStatement();
                c.sentencia.execute("insert into alumno("
                        + "nom_alu, "
                        + "usu_alu, "
                        + "pas_alu, "
                        + "cod_sec, "
                        + "ano_alu, "
                        + "ema_alu) values("
                        + "'"+u.getNombre()+"',"
                + "'"+u.getNombreUsuario()+"',"
                + "'"+u.getPass()+"',"
                + "'"+s.getCodigo()+"',"
                + "'2012',"
                + "'"+u.getMail()+"')");
                c.sentencia.close();
            } catch (SQLException ex) {
                Logger.getLogger(Apli.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
        
    }

    private void updatearClave(String tabla , String campo, String clave) {
        try {
            c.sentencia = c.con.createStatement();
            c.sentencia.execute("update "+tabla+" set "+campo+" = '"+clave+"'");
            c.sentencia.close();
        } catch (SQLException ex) {
            Logger.getLogger(Apli.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    private void insertarProfesor(Director d, int cantidad) {
        boolean e = false;
        List<Usuario> usuarios = Generar.usuarios(cantidad);
        for(Usuario u:usuarios){
            try {
                if(d.getCodigoSede().equalsIgnoreCase("14") && !e){//Rancagua
                    u.setNombre("Esteban Valenzuela Castro");
                    u.setNombreUsuario("evalenzuela");
                    u.setMail("patodeath@gmail.com");
                    e = true;
                }
                
                if (Buscar.isProfesor(u.getNombreUsuario())) {
                    int numeroSiguiente = Buscar.getNextContador("profesor", "usu_pro", u.getNombreUsuario());
                    u.setNombreUsuario(u.getNombreUsuario()+numeroSiguiente);
                }
                
                c.sentencia = c.con.createStatement();
                c.sentencia.execute("insert into profesor "
                        + "(nom_pro, usu_pro, pas_pro, cod_dir, ema_pro, est_pro) "
                        + "values('"+u.getNombre()+"',"
                        + "'"+u.getNombreUsuario()+"',"
                        + "'"+u.getPass()+"',"
                        + "'"+d.getCodigo()+"',"
                        + "'"+u.getMail()+"','vigente')");
                c.sentencia.close();
            } catch (SQLException ex) {
                Logger.getLogger(Apli.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
//        
    }
}
